---
camera:
    fx: 1390.53
    fy: 1386.99
    cx: 964.957
    cy: 522.586
    im_width: 1920
    im_height: 1080
scene:
    path_img: data/avocado/scene/149_rgb.jpg
    path_depth: data/avocado/scene/149_depth.png
    path_segmentation: data/avocado/scene/149_seg.png
    image_resize: 0.5
object3d:
    position: [0.3, -0.2, 0.8]
    scale: 0.01
    rotation: [
        [0.62753633, 0.47449067, 0.61729685],
        [-0.76647104, 0.23716558, 0.59688741],
        [0.13681571, -0.84771019, 0.51251286]
    ]
    model_path: data/avocado/mesh/avocado2_mesh.ply
losses:
    l1_rgb_with_mask: false
    weight_rgb: 0.7
    l1_depth_with_mask: false
    weight_depth: 1
    l1_mask: true
    weight_mask: 1
hyperparameters:
    nb_iterations: 600
    batchsize: 8
    base_lr: 20
    learning_rates_bound: [0.01, 100]
    learning_rate_base: 1
    lr_decay: 0.1
render_images:
    nrow: 4
    final_width_batch: 2000
    add_background: true
    alpha_overlay: 0.7
    add_countour: true
    color_countour: [0.46, 0.73, 0]
    flip_result: true
    crop_around_mask: true
